name: (Feature) Pre Build Checks
on:
  push:
    branches:
      - '**'

jobs:
  test:
    continue-on-error: false
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [dev]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests With Coverage
        id: test
        run: go test -cover -count=1 ./...

  golangci-lint:
    continue-on-error: false
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [dev]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.42
          # Optional: working directory, useful for monorepos
          # working-directory: somedir
          # Optional: golangci-lint command line arguments.
          args: --timeout=2m
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
          # Optional: if set to true then the action will use pre-installed Go.
          # skip-go-installation: true
          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true
          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
