name: Tests & Linting
on:
  push:
    branches:
      - '**'
env:
  GOPRIVATE: github.com/eyewa/eyewa-go-lib
  GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

jobs:
  gosec:
    runs-on: [self-hosted, dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
  test:
    continue-on-error: false
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [dev]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests With Coverage
        id: test
        run: go test -cover -count=1 ./...

  golangci-lint:
    continue-on-error: false
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [dev]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Private Go library auth
        run:  git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.42
          # Optional: working directory, useful for monorepos
          # working-directory: somedir
          # Optional: golangci-lint command line arguments.
          args: --timeout=2m
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
          # Optional: if set to true then the action will use pre-installed Go.
          # skip-go-installation: true
          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true
          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
